spring:
  datasource:
    url: jdbc:h2:mem:credit_application_system_db
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: true
